services:
  - type: web
    name: career-copilot-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
